# SPDX-License-Identifier: AGPL-3.0-or-later
# 3.5 节：mira-plugin-cli 独立版本（packageFormatVersion 独立于 pluginApi）。
# 不再使用 workspace.version，CLI 有自己的发布周期和 tag（mira-plugin-cli-v*）。
# 版本号遵循项目规则：不得含数字 4 或 11。
[package]
name = "mira-plugin-cli"
version = "1.0.2"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "mira-plugin"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
base64 = "0.23"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
clap.workspace = true
ed25519-dalek = { workspace = true, features = ["pkcs8", "pem"] }
hex.workspace = true
mira-plugin-api = { path = "../mira-plugin-api" }
mira-plugin-runtime = { path = "../mira-plugin-runtime" }
rand = "0.10"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
walkdir.workspace = true
zip.workspace = true
